#!/bin/sh
echo Cleaning...
rm -f cmdline.o comptime.h encoding.o err.o fileio.o help.o lxlogic.o messages.o mslogic.o oshw-qt/_in.o oshw-qt/_sdlsfx.o oshw-qt/CCMetaData.o oshw-qt/generic.o oshw-qt/moc_TWMainWnd.cpp oshw-qt/moc_TWMainWnd.o oshw-qt/oshwbind.o oshw-qt/tile.o oshw-qt/timer.o oshw-qt/TWApp.o oshw-qt/TWDisplayWidget.o oshw-qt/TWMainWnd.o oshw-qt/TWProgressBar.o oshw-qt/ui_TWMainWnd.h play.o random.o res.o score.o series.o settings.o solution.o tworld.o tworld2 unslist.o
